export const Fonts = {
    'Gotham-Medium': 'GothamHTF-Medium',
    'Gotham-Bold': 'Gotham-Bold',
    'Gotham-Book': 'GOTHAMBOOK',
    'Rocky-Regular': 'Rocky-Regular',
    'Rocky-Bold': 'Rocky-Bold',
    'SF Pro Display': 'SFProText-Regular',
    'Gotham-Ultra': 'Gotham-Ultra',
    'Rocky-Medium': 'Rocky-Medium',
    'SFProText-Regular': 'SFProText-Regular',
    'Gotham-Light': 'Gotham-Light',
    'Gotham-BoldItalic': 'Gotham-BoldItalic',
    'Gotham-Bold-Italic': 'Gotham-Bold-Italic',
    'ArialTh': 'ArialTh',
    'brush-script-mt-kursiv': 'brush-script-mt-kursiv',
    'Calibri': 'Calibri',
    'CONSOLA': 'CONSOLA',
    'cour': 'cour',
    'Gabriola': 'Gabriola',
    'GOUDOS': 'GOUDOS',
    'Inkfree': 'Inkfree',
    'LHANDW': 'LHANDW',
    'Lucida-Sans': 'Lucida-Sans',
    'MINGLIU': 'MINGLIU',
    'ROCK': 'ROCK',
    'times-new-roman': 'times-new-roman',
};
