export const Peoples = [
    {
        id: 0,
        firstname: `asad`,
        lastname: `mumtaz`,
        phone: `333-666-3896`,
        desig: `React Native Developer`,
        company: `Web Technologies`,
        project: `CRM Project`,
        note: `This is note for Asad Mumtaz`,
        image: `https://www.superoffice.com/contentassets/4ea5c9a357e1497db015d857890fcea3/crm-strategy.jpg`,
    },
    {
        id: 1,
        firstname: `shahmir`,
        lastname: `alam`,
        phone: `333-844-4051`,
        desig: `Full Stack Developer`,
        company: `StlllR Media`,
        project: `Pick Me Up Anywhere`,
        note: `This is note for Shahmir Alam`,
        image: `https://dm3z1jexb3zz4.cloudfront.net/public/images/core/Images/Wordpress-Archive/uploads/2016/01/CRM.png`,
    },
    {
        id: 2,
        firstname: `munem`,
        lastname: `habib`,
        phone: `444-555-6666`,
        desig: `React Native Developer`,
        company: `YSTL`,
        project: `CircleIt`,
        note: `This is note for Munem Habib`,
        image: ``, // `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQum03Clx7JnxQEx4ymPJdw9fkZwglumr1TFvNjHh1Lxl3exMc1B4p4iR6JnilsmnT7ciU&usqp=CAU`,
    },
    {
        id: 3,
        firstname: `muhammad`,
        lastname: `mohsin`,
        phone: `444-555-6666`,
        desig: `UI/UX Designer`,
        company: `Figma Design`,
        project: `Celfic`,
        note: `This is note for Munem Habib`,
        image: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQum03Clx7JnxQEx4ymPJdw9fkZwglumr1TFvNjHh1Lxl3exMc1B4p4iR6JnilsmnT7ciU&usqp=CAU`,
    },
    {
        id: 4,
        firstname: `muhammad`,
        lastname: `yahya`,
        phone: `444-555-6666`,
        desig: `Support Represantatie`,
        company: `CEO Tech`,
        project: `Travel In Bermuda`,
        note: `This is note for Munem Habib`,
        image: ``, // `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQum03Clx7JnxQEx4ymPJdw9fkZwglumr1TFvNjHh1Lxl3exMc1B4p4iR6JnilsmnT7ciU&usqp=CAU`,
    },
]
