  
export const PostData = [
    {
        id: 1,
        images: [
            'https://newlaunch-my.ippstatic.com/live/MY/showunit/640/6543_321362_1683074914.jpg',
            'https://cdn.globalpropertyguide.com/assets/USA-2/US-2023.jpg',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLBSguFJP6wh9cEcJ0Pw_Pprtu794cwvMoSA&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlv-oiUN0M4nT5e_Dxz9mUDEl6Gfu_mkzGpg&usqp=CAU',
        ],
        title: 'Luxary appartment for Sale.',
        desc: 'Appartment detail below vknrj kfjnvliu yu gcyt yct vyt vt vjyc mkiuiu yhuyrf buyure uubyyuv c reuyu jhbvhghh hb gug ftgtg tg ftgwug ufwg ef',
        city: 'Islamabad',
        society: 'Bahria Enclave',
        sector: 'C1',
        size: '8 Marla',
        demand: '37000000',
        category: 'Commercial',
        type: 'Sale',
        visibility: 'Public',
        contact: '+92 3336663896'
    },
    {
        id: 2,
        images: [
            'https://cdn.globalpropertyguide.com/assets/USA-2/US-2023.jpg',
            'https://newlaunch-my.ippstatic.com/live/MY/showunit/640/6543_321362_1683074914.jpg',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLBSguFJP6wh9cEcJ0Pw_Pprtu794cwvMoSA&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlv-oiUN0M4nT5e_Dxz9mUDEl6Gfu_mkzGpg&usqp=CAU',
        ],
        title: 'House for rent',
        desc: '- House \n- road 2 \n- brand new \n- upper portion \n- only for small family',
        city: 'Islamabad',
        society: 'Bahria Enclave',
        sector: 'H',
        size: '5 Marla',
        demand: '50000',
        category: 'Residencial',
        type: 'Rent',
        visibility: 'Public',
        contact: '+92 3338444015'
    },
    {
        id: 3,
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLBSguFJP6wh9cEcJ0Pw_Pprtu794cwvMoSA&usqp=CAU',
            'https://newlaunch-my.ippstatic.com/live/MY/showunit/640/6543_321362_1683074914.jpg',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlv-oiUN0M4nT5e_Dxz9mUDEl6Gfu_mkzGpg&usqp=CAU',
            'https://cdn.globalpropertyguide.com/assets/USA-2/US-2023.jpg',
        ],
        title: 'Luxary house for rent',
        desc: 'House detail below vknrj kfjnvliu yu gcyt yct vyt vt vjyc mkiuiu yhuyrf buyure uubyyuv c reuyu jhbvhghh hb gug ftgtg tg ftgwug ufwg ef',
        city: 'Karachi',
        society: 'DHA',
        sector: 'Phase 8',
        size: '1 Kanal',
        demand: '300000',
        category: 'Residencial',
        type: 'Rent',
        visibility: 'Public',
        contact: '+92 3338444015'
    },
    {
        id: 4,
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlv-oiUN0M4nT5e_Dxz9mUDEl6Gfu_mkzGpg&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLBSguFJP6wh9cEcJ0Pw_Pprtu794cwvMoSA&usqp=CAU',
            'https://cdn.globalpropertyguide.com/assets/USA-2/US-2023.jpg',
            'https://newlaunch-my.ippstatic.com/live/MY/showunit/640/6543_321362_1683074914.jpg',
        ],
        title: 'Shop for sale.',
        desc: '- House - road 2 - brand new - upper portion - only for small family',
        city: 'islamabad',
        society: 'Park View City',
        sector: 'D',
        size: '12x30',
        demand: '13500000',
        category: 'Commercial',
        type: 'Sale',
        visibility: 'Public',
        contact: '+92 3336663896'
    },
]
