export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY' // done

export const SET_SELECTED_MEAL = 'SET_SELECTED_MEAL' // done

export const ADD_FAVORITE_MEAL = 'ADD_FAVORITE_MEAL' // done

export const INCREEMENT = 'INCREEMENT' // done

export const DECREEMENT = 'DECREEMENT' // done


// BLOG APP
export const GET_ALL_DEALS = 'GET_ALL_DEALS'

export const SELECTED_DEAL = 'SELECTED_DEAL'

// CRM
export const CRM = "CRM"

export const SELECTED_PEOPLES = "SELECTED_PEOPLES"

export const SELECTED_COMPANIES = "SELECTED_COMPANIES"


// IBRAHIM ASSOCIATE
export const IB_ALL_POST = 'IB_ALL_POST'

export const IB_SELECTED_POST = 'IB_SELECTED_POST'
